kind: Service
apiVersion: v1beta3
metadata:
  name: osswebapp
  labels:
    name: osswebapp
spec:
  ports:
    - port: 5000
      targetPort: osswebapp-http-port
      protocol: TCP
      name: osswebapp-http-port
  selector:
    name: osswebapp
  createExternalLoadBalancer: true
